### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by SgtPunishment** [TeamWhammich/Resonant-Randomiser#1]
Resonant Randomiser TODO List

High Priority
- [x] Bag inventory saving and shift+click bug
- [x] Advanced gui (9, 27 & 54 slots respectfully)

Medium Priority
- [ ] Grab blocks from the bags with NBT to place
- [ ] Prevent Tile Entities been placed
- [ ] Only allow blocks in the bags
- [ ] Block weight via stack size probability of placement
- [ ] Tool radius selector
- [ ] Tool radius highlighting
- [ ] Agree on block placing maths
- [ ] Come up with recipes for the tools and bags

Low Priority
- [x] Textures (4 tools, 3 bags)
- [x] Localization
